//
//  DTOStyleKit.h
//  Dato
//
//  Created by Alexander Kolov on 13/05/14.
//  Copyright (c) 2014 Alexander Kolov. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>


@interface DTOStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* cogwheelTargets;

// Colors
+ (UIColor*)translucentForegroundWhite;
+ (UIColor*)foregroundBlueColor;
+ (UIColor*)foregroundYellowColor;
+ (UIColor*)foregroundOrangeColor;
+ (UIColor*)foregroundRedColor;
+ (UIColor*)foregroundGrayColor;
+ (UIColor*)foregroundDarkGrayColor;
+ (UIColor*)backgroundGrayColor;
+ (UIColor*)backgroundDarkGrayColor;
+ (UIColor*)backgroundWhiteColor;
+ (UIColor*)backgroundBlackColor;
+ (UIColor*)foregroundSilverColor;
+ (UIColor*)separatorGrayColor;
+ (UIColor*)separatorDarkGrayColor;

// Drawing Methods
+ (void)drawCogwheel;

// Generated Images
+ (UIImage*)imageOfCogwheel;

@end
